# Generated by Django 4.2.4 on 2023-09-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="No Title", max_length=255)),
                ("content", models.TextField(blank=True)),
                ("deleted", models.BooleanField(default=False)),
                ("by", models.CharField(blank=True, max_length=150)),
                ("time", models.DateTimeField(blank=True)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("job", "job"),
                            ("story", "story"),
                            ("comment", "comment"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("hackernews", "Hacker News"), ("user", "User")], default="hackernews", max_length=20
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("by", models.CharField(blank=True, max_length=150)),
                ("time", models.DateTimeField(blank=True)),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.story")),
            ],
        ),
    ]
